Entry.create!(name: "Jared")
Entry.create!(name: "Colleen")
Entry.create!(name: "Ali")
Entry.create!(name: "Mj")
Entry.create!(name: "Ahmad")
Entry.create!(name: "Saeed")
Entry.create!(name: "Mrs. Shiflet")